name: Boots and Cats
favicon: null
layout_spectrum: 0.4162803334183991
typography_spectrum: 0.6026177168823779
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7064676529262215
  lightness: 0.4335766676813364
  saturation: 0.6979368275497109
  rhythmicContrast: 0.24507586448453367
purpose: []
